SELECT
YEAR(o.SALES_DATE) AS YEAR,
MONTH(o.SALES_DATE) AS MONTH,
u.GENDER,
COUNT(DISTINCT u.USER_ID) AS USERS
FROM USER_INFO u JOIN ONLINE_SALE o
ON u.USER_ID = o.USER_ID AND u.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER

# SELECT o.SALES_DATE, u.GENDER
# FROM USER_INFO u JOIN ONLINE_SALE o
# ON u.USER_ID = o.USER_ID AND u.GENDER IS NOT NULL
# ORDER BY SALES_DATE, GENDER