SELECT YEAR,
(e2.MAX_LENGTH - SIZE_OF_COLONY) AS YEAR_DEV,
e1.ID
FROM ECOLI_DATA e1
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_LENGTH
        FROM ECOLI_DATA
        GROUP BY YEAR) e2
ON YEAR(e1.DIFFERENTIATION_DATE) = e2.YEAR
ORDER BY YEAR, YEAR_DEV